sudo micro /etc/resolv.conf

# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
# nameserver 192.168.1.254
nameserver 114.114.114.114


## update packages via terminal
sudo apt install -y l*gls* libcatalyst-action-rest-perl libghc-hmatrix-doc libghc-storable-complex-doc libghc-hmatrix-doc libcatalyst-action-serialize-data-serializer-perl

sudo su - -c "R -e \"install.packages(c('devtools', 'tidyverse', 'miniUI', 'splashr', 'nloptr', 'lme4', 'MEMSS', 'mlmRev', 'gamm4', 'pbkrtest', 'rr2', 'semEff', 'car', 'crayon', 'languageserver', 'ghit', 'mosaic', 'RgoogleMaps', 'openssl', 'RcppArmadillo', 'roxygen2', 'tinytex', 'xfun', 'BiocManager', 'rgl', 'rJava', 'rJava', 'OpenStreetMap', 'loa', 'sodium', 'magick'), repos='https://cran.rstudio.org', lib='/usr/lib/R/library', dependencies = c('Depends', 'Imports'), INSTALL_opts = '--no-lock')\""

sudo su - -c "R -e \"devtools::install_github('cloudyr/MTurkR', force = TRUE)\""

sudo su - -c "R -e \"install.packages(c('languageserver'), repos='http://R-Forge.R-project.org', lib='/usr/lib/R/library', dependencies = c('Depends', 'Imports'), INSTALL_opts = '--no-lock')\""

install.packages(c('SkewHyperbolic', 'Rmetrics'), repos='http://R-Forge.R-project.org', lib='/usr/lib/R/library', dependencies = c('Depends', 'Imports'), INSTALL_opts = '--no-lock')

sudo su - -c "R -e \"devtools::install_github('stan-dev/rstanarm', INSTALL_opts = '--no-multiarch', force = TRUE)\""

sudo su - -c "R -e \"devtools::install_github('stan-dev/rstanarm', INSTALL_opts = '--no-lock', force = TRUE)\""

install.packages('rstanarm', repos = c('https://mc-stan.org/r-packages/', getOption('repos')))

sudo su - -c "R -e \"devtools::install_github('cloudyr/googleCloudStorageR', INSTALL_opts = '--no-lock', force = TRUE)\""

sudo su - -c "R -e \"install.packages('BBmisc', getOption('repos'), lib='/usr/lib/R/library', dependencies = TRUE, INSTALL_opts = '--no-lock')\""

## https://www.reddit.com/r/rstats/comments/hiu17b/can_i_delete_outdated_r_version/
sudo su - -c "R -e \"install.packages(rownames(installed.packages(priority = 'NA')), getOption('repos'), lib='/usr/lib/R/library', dependencies = TRUE, INSTALL_opts = '--no-lock')\""

sudo su - -c "R -e \"devtools::update_packages()\""
sudo su - -c "R -e \"update.packages(ask=FALSE)\""


## ===========================================================
## list all r packages 
require('tidyverse')
require('xml2')
require('rvest')
require('stringr')
require('magrittr')
require('plyr')
require('dplyr')
require('devtools')

rp <- 'https://cloud.r-project.org/src/contrib/'
pkg <- rp %>% 
  read_html %>% 
  html_nodes('a') %>% 
  html_attr('href')
pkg <- pkg[136:length(pkg)]

# pkg[1:10] %>% 
#llply(., function(x) {
#  y <- paste0(rp, x)
#  z <- paste0("download.file(url = ", y, ", destfile = paste0('/home/englianhu/Downloads/", x,"))")
#  eval(z)
#})

pkg %>% 
  llply(., function(x) {
    y <- paste0(rp, x)
    fl <- paste0('/home/englianhu/Downloads/', x)
    download.file(url = y, destfile = fl)
    install.packages(fl, repos = NULL, type = 'source')
    #install.packages(file.choose(fl), repos = NULL, type = 'source')
    #install_local(path = fl)
    file.remove(fl)
  })


